-- Decompiled using luadec 2.1 UNICODE r69 from http://code.google.com/p/luadec
-- Command line: achiev_cond_def.luac 

local _t = require("i18n").context("achievement")
achiev_cond_def = {
[1] = {client_check = 0, desc = _t("1°morte")}, 
[2] = {client_check = 0, desc = _t("1°matrimonio")}, 
[3] = {client_check = 1, desc = _t("1°apprendista")}, 
[4] = {client_check = 1, desc = _t("1° raccolta")}, 
[5] = {client_check = 1, desc = _t("Crea/entra in una gilda")}, 
[6] = {client_check = 1, desc = _t("1°report di errore")}, 
[7] = {client_check = 1, desc = _t("1°repert di abuso")}, 
[8] = {client_check = 1, desc = _t("1°stella")}, 
[9] = {client_check = 1, desc = _t("1°kill di un cavaliere")}, 
[10] = {client_check = 1, desc = _t("1°ruolo attivo")}, 
[11] = {client_check = 1, desc = _t("Ntilizzato VoiceTeam per la 1°volta")}, 
[12] = {client_check = 1, desc = _t("1°amico")}, 
[13] = {client_check = 1, desc = _t("1°gruppo")}, 
[14] = {client_check = 1, desc = _t("1°liv. manuale")}, 
[15] = {client_check = 1, desc = _t("1°volta in chat gilda")}, 
[16] = {client_check = 1, desc = _t("1°trasferimento di equip.")}, 
[17] = {client_check = 1, desc = _t("1° atterraggio")}, 
[18] = {client_check = 1, desc = _t("1°doppia exp")}, 
[19] = {client_check = 1, desc = _t("1° skill")}, 
[20] = {client_check = 1, desc = _t("1° vittoria")}, 
[21] = {client_check = 1, desc = _t("1°azione")}, 
[22] = {client_check = 1, desc = _t("1°negoziazione")}, 
[23] = {client_check = 1, desc = _t("1°asta")}, 
[24] = {client_check = 1, desc = _t("1°scambio di armatura")}, 
[25] = {client_check = 1, desc = _t("1° venditore")}, 
[26] = {client_check = 1, desc = _t("1°acquisto")}, 
[27] = {client_check = 1, desc = _t("1°vendita")}, 
[28] = {client_check = 1, desc = _t("1°acquisto da un altro venditore")}, 
[29] = {client_check = 1, desc = _t("1°blocco orario")}, 
[30] = {client_check = 1, desc = _t("1°password registrata")},
[31] = {client_check = 1, desc = _t("1°classe scelta")},
[32] = {client_check = 1, desc = _t("1° Skill appresa")}, 
[33] = {client_check = 1, desc = _t("1°apertura del cosmo")}, 
[34] = {client_check = 1, desc = _t("1°utilizziazione del cosmo")}, 
[35] = {client_check = 1, desc = _t("1°utilizziazione del cosmo")}, 
[36] = {client_check = 1, desc = _t("1°runa usata")}, 
[37] = {client_check = 1, desc = _t("1°equip disincantata")}, 
[38] = {client_check = 1, desc = _t("1°volta che usi il box")}, 
[39] = {client_check = 1, desc = _t("1°divisione dell'item")}, 
[40] = {client_check = 1, desc = _t("1°invocazione dell'armatura")}, 
[41] = {client_check = 1, desc = _t("Gloria dell'oceano")}, 
[42] = {client_check = 1, desc = _t("1°coupons spesi")}, 
[43] = {client_check = 1, desc = _t("1°titolo ottenuto")}, 
[44] = {client_check = 1, desc = _t("1°volta che usi interfaccia gilda")}, 
[101] = {client_check = 0, desc = _t("Completa una conquista")}, 
[102] = {client_check = 0, desc = _t("Persona raggiunta")}, 
[103] = {client_check = 0, desc = _t("Lvl 1 Cosmo raggiunto")}, 
[104] = {client_check = 0, desc = _t("attività completata")}, 
[105] = {client_check = 0, desc = _t("ID Mobs")}, 
[106] = {client_check = 0, desc = _t("prestigio raggiunto")}, 
[107] = {client_check = 0, desc = _t("Prestige Lvl Up atteint")}, 
[108] = {client_check = 0, desc = _t("Vittorie")}, 
[109] = {client_check = 0, desc = _t("PvP convalidato")}, 
[110] = {client_check = 0, desc = _t("Somme raggiunte")}, 
[111] = {client_check = 0, desc = _t("Somme raggiunte")}, 
[112] = {client_check = 0, desc = _t("Combattimento finito")}, 
[113] = {client_check = 0, desc = _t("Titolo appreso")}, 
[114] = {client_check = 0, desc = _t("titolo specifico")}, 
[115] = {client_check = 0, desc = _t("Ottieni immagine")}, 
[116] = {client_check = 0, desc = _t("Armatura ottenuta")}, 
[117] = {client_check = 0, desc = _t("Ottenere un armatura")}, 
[118] = {client_check = 0, desc = _t("Numero amici")}, 
[119] = {client_check = 0, desc = _t("aumentare il livello di amicizia")}, 
[120] = {client_check = 0, desc = _t("Ladro ucciso")}, 
[121] = {client_check = 0, desc = _t("VIP")}, 
[122] = {client_check = 0, desc = _t("Equip/Attivita Vittorie")}, 
[123] = {client_check = 0, desc = _t("Segnalare Abuso")}, 
[124] = {client_check = 0, desc = _t("Rapport Erreur Nb lvl atteint")}, 
[125] = {client_check = 0, desc = _t("Ottenuta cavalcatura")}, 
[126] = {client_check = 0, desc = _t("Il tuo amico ha una cotta per te")}, 
[127] = {client_check = 0, desc = _t("Mappa che rappresenta il numero di kill che il pg deve raggiungere")}, 
[128] = {client_check = 0, desc = _t("Raggiungi il livello")}, 
[129] = {client_check = 0, desc = _t("En PvP Lent Battre le temps de son coéquipier(Challenge)")}, 
[130] = {client_check = 0, desc = _t("En PvP Lent Nbre victoires cons.(knockout)")}, 
[131] = {client_check = 0, desc = _t("En PvP Lent Classement (knockout)")}, 
[132] = {client_check = 0, desc = _t("Produrre per completare lvl")}, 
[133] = {client_check = 0, desc = _t("Aumentare  liv. armat.")}, 
[134] = {client_check = 0, desc = _t("Punteggio cosmo raggiunto")}, 
[135] = {client_check = 0, desc = _t("Perfetto")}, 
[136] = {client_check = 0, desc = _t("Acquista numero ID")}, 
[1001] = {client_check = 0, desc = _t("Ogg.per completare la quest")}, 
[1002] = {client_check = 0, desc = _t("Ogg.per completare alcune quest")}, 
[1003] = {client_check = 0, desc = _t("Ogg.per completare qualche subquests")}, 
[1004] = {client_check = 0, desc = _t("Ogg.per completare alcune quest")}, 
[1005] = {client_check = 0, desc = _t("Mobs")},
[1006] = {client_check = 0, desc = _t("Apprendi la skill al liv.corrispondente")}, 
[1007] = {client_check = 0, desc = _t("Numero di apprendisti")}, 
[1008] = {client_check = 0, desc = _t("Numero di vittorie")}, 
[1009] = {client_check = 0, desc = _t("Vittorie PvP")}, 
[1010] = {client_check = 0, desc = _t("collezzione")},
[1011] = {client_check = 0, desc = _t("Illustrazioni")}}

