-- Decompiled using luadec 2.1 r80 from http://code.google.com/p/luadec
-- Command line: C:\Users\Reloa\Desktop\sso translation\newpatch\script\itemdesc\itemdesctext.lua 

local _t = require("i18n").context("item")
ITEM_COLOR_DESC = {}
ITEM_COLOR_DESC.Gray = "^a1a3a4"
ITEM_COLOR_DESC.White = "^f2f3f2"
ITEM_COLOR_DESC.Green = "^00ff00"
ITEM_COLOR_DESC.Purple = "^a800ff"
ITEM_COLOR_DESC.Orange = "^e5872f"
ITEM_COLOR_DESC.Yellow = "^ffff00"
ITEM_COLOR_DESC.Red = "^ff0000"
ITEM_COLOR_DESC.Blue = "^0184ff"
ITEM_COLOR_DESC.DarkYellow = "^ffc000"
ITEM_COLOR_DESC.LightBlue = "^00d2ff"
ITEM_COLOR_DESC.PetSkill = "^c0c0ff"
ITEM_COLOR_DESC.Brown = "^BDB76B"
ITEM_COLOR_DESC.Enhance = "^45d8ff"
ITEM_COLOR_DESC.TestColor = "^ffff00"
ITEM_COLORSTR = {}
ITEM_COLORSTR[0] = STRING_TABLE.ITEMQUALITY_COL_0
ITEM_COLORSTR[1] = STRING_TABLE.ITEMQUALITY_COL_1
ITEM_COLORSTR[2] = STRING_TABLE.ITEMQUALITY_COL_2
ITEM_COLORSTR[3] = STRING_TABLE.ITEMQUALITY_COL_3
ITEM_COLORSTR[4] = STRING_TABLE.ITEMQUALITY_COL_4
ITEM_COLORSTR[5] = STRING_TABLE.ITEMQUALITY_COL_5
ITEM_COLORSTR[6] = STRING_TABLE.ITEMQUALITY_COL_6
ITEM_COLORSTR[7] = STRING_TABLE.ITEMQUALITY_COL_7
ITEM_COLORSTR[8] = STRING_TABLE.ITEMQUALITY_COL_8
ITEM_COLORSTR[9] = STRING_TABLE.ITEMQUALITY_COL_9
ITEM_GUIDE_LINK_DESC = {}
ITEM_GUIDE_LINK_DESC.LINK = _t("包裹中左键点击寻路,相关: ^U00FF00%s%s^u")
ITEM_SIZE_DESC = {}
ITEM_SIZE_DESC.Size10 = "^O001"
ITEM_SIZE_DESC.Size12A = "^O013"
ITEM_SIZE_DESC.Size12 = "^O013"
ITEM_SIZE_DESC.Size10A = "^O041"
ITEM_SIZE_DESC.Size9 = "^O109"
ITEM_SIZE_DESC.Size8 = "^O110"
ITEM_SIZE_DESC.Size11 = "^O114"
ITEM_PROC_MASK_DESC = {}
ITEM_PROC_MASK_DESC.Mask1 = _t("不可出售\r")
ITEM_PROC_MASK_DESC.Mask2 = _t("不可交易\r")
ITEM_PROC_MASK_DESC.Mask3 = nil
ITEM_PROC_MASK_DESC.Mask4 = nil
ITEM_PROC_MASK_DESC.Mask5 = _t("装备后绑定\r")
ITEM_PROC_MASK_DESC.Mask6 = _t("直接绑定\r")
ITEM_PROC_MASK_DESC.Mask7 = _t("不可存放仓库\r")
ITEM_PROC_MASK_DESC.Mask8 = _t("不可销毁\r")
ITEM_PROC_MASK_DESC.Mask9 = _t("切换场景消失后消失\r")
ITEM_PROC_MASK_DESC.Mask10 = _t("红名死亡后消失\r")
ITEM_PROC_MASK_DESC.Mask11 = _t("拾取后绑定\r")
ITEM_PROC_MASK_DESC.Mask_Bound1 = _t("不可出售\r")
ITEM_PROC_MASK_DESC.Mask_Bound2 = nil
ITEM_PROC_MASK_DESC.Mask_Bound3 = nil
ITEM_PROC_MASK_DESC.Mask_Bound4 = nil
ITEM_PROC_MASK_DESC.Mask_Bound5 = nil
ITEM_PROC_MASK_DESC.Mask_Bound6 = nil
ITEM_PROC_MASK_DESC.Mask_Bound7 = _t("不可存放仓库\r")
ITEM_PROC_MASK_DESC.Mask_Bound8 = _t("不可销毁\r")
ITEM_PROC_MASK_DESC.Mask_Bound9 = nil
ITEM_PROC_MASK_DESC.Mask_Bound10 = nil
ITEM_PROC_MASK_DESC.Mask_Bound11 = nil
ITEM_NAME_DESC = {}
ITEM_NAME_DESC.Name = "%s "
ITEM_NAME_DESC.Name1 = "%s +%d"
ITEM_NAME_DESC.NameLevel = _t("需求%s %d级")
ITEM_COUNT_DESC = {}
ITEM_COUNT_DESC.Count = _t("（%d）")
ITEM_COUNT_DESC.MaxHold = _t("%s最多可携带%d个")
ITEM_BOUND_DESC = {}
ITEM_BOUND_DESC.Bound = _t("已绑定\r")
ITEM_BOUND_DESC.Bound1 = _t("装备后绑定\r")
ITEM_TIME_DESC = {}
ITEM_TIME_DESC.ExpireTime = _t("剩余时间 ")
ITEM_TIME_DESC.Day = _t("%dg")
ITEM_TIME_DESC.Hour = _t("%dH")
ITEM_TIME_DESC.Minute = _t("%dm")
ITEM_TIME_DESC.Second = _t("%ds")
ITEM_TIME_DESC.ValidTime = _t("持续时间 ")
ITEM_TIME_DESC.ColddownTime = _t("Cooldown ")
ITEM_TIME_DESC.ExpireColddownTime = _t("剩余冷却时间 ")
ITEM_COMPOSE_DESC = {}
ITEM_COMPOSE_DESC.CANNOT = _t("不可分解\r")
ITEM_PRICE_DESC = {}
ITEM_PRICE_DESC.PriceTotalPrice = _t("价格 %s\r")
ITEM_PRICE_DESC.PriceTotalPrice1 = _t("价格 %s (%s)\r")
ITEM_PRICE_DESC.PriceTotalPrice2 = _t("价格 %s\r或者 %s\r")
ITEM_PRICE_DESC.PriceTotalPrice3 = _t("价格 %s (%s)\r或者 %s (%s)\r")
ITEM_PRICE_DESC.Price = _t("价格 %s")
ITEM_PRICE_DESC.Price1 = _t("价格 %s (%s)")
ITEM_PRICE_DESC.Repair = _t("修理费 %s\r")
ITEM_PRICE_DESC.ItemCost = _t("需要 %s × %d ")
ITEM_PRICE_DESC.ItemCost1 = _t("需要 %s × %d ")
ITEM_PRICE_DESC.PrestigePrice = _t("消耗 %s %d ")
ITEM_PRICE_DESC.ReqPrestigeCount = _t("需求 %s %d阶 ")
ITEM_PRICE_DESC.Empty = ""
ITEM_LEARNED_DESC = {}
ITEM_LEARNED_DESC.Learned = _t("已学会\r")
ITEM_RECIPE_DESC = {}
ITEM_RECIPE_DESC.Exp = _t("学习消耗经验%d")
ITEM_RECIPE_DESC.PlayerLev = _t("学习需要玩家达到%s\r")
ITEM_RECIPE_DESC.Coin = _t("学习消耗金钱%d")
ITEM_REQ_LEVEL_DESC = {}
ITEM_REQ_LEVEL_DESC.ReqLevel = _t("要求等级  %d\r")
ITEM_REQ_LEVEL_DESC.ReqLevel2 = _t("要求潜修等级  %d\r")
ITEM_REQ_COSMOS_LEVEL_DESC = {}
ITEM_REQ_COSMOS_LEVEL_DESC.ReqCosmosLevel = _t("要求小宇宙等级  %d\r")
ITEM_TAKE_BOUNTY_REQ_LEVEL_DESC = {}
ITEM_TAKE_BOUNTY_REQ_LEVEL_DESC.TakeBountyReqLevel = _t("携带等级  %s\r")
ITEM_SUMMON_LEVEL_LIMIT = {}
ITEM_SUMMON_LEVEL_LIMIT.Summon_Level_Limit = _t("适用携带等级不超过%d的宠物\r")
ITEM_USE_TIMES_DESC = {}
ITEM_USE_TIMES_DESC.UseTimes = _t("使用次数 %d\r")
FIGHT_POWER = _t("★战力 %d\r")
ITEM_BOUND_DEAD_DESC = {}
ITEM_BOUND_DEAD_DESC.DEAD = _t("死亡\r")
ITEM_BOUND_TRAIN_DESC = {}
ITEM_BOUND_TRAIN_DESC.Train = _t("已修炼\r")
ITEM_BOUND_TRAIN_DESC.NotTrain = _t("未修炼\r")
ITEM_BOUNTY_REQ_PRESTIGE_DESC = {}
ITEM_BOUNTY_REQ_PRESTIGE_DESC.BountyReqPrestige = _t("声望限制 %d\r")
ITEM_BOUNTY_POINT_DESC = {}
ITEM_BOUNTY_POINT_DESC.BountyPoint = _t("评分 %d\r")
ITEM_PET_SKILL = {}
ITEM_PET_SKILL.Prob = _t("学习成功率 %d%%\r")
ITEM_PET_SKILL.AvForType_0 = _t("%s近程%s宠物专用技能书\r")
ITEM_PET_SKILL.AvForType_1 = _t("%s远程%s宠物专用技能书\r")
ITEM_PET_SKILL.AvForType_2 = _t("%s通用%s宠物技能书\r")
ITEM_DICE_CET_DESC = {}
ITEM_DICE_CET_DESC.DiceCnt = _t("抽取次数 %d\r")
ITEM_MORE_SEATER_RIDES_DESC = {}
ITEM_MORE_SEATER_RIDES_DESC.MoreSeaterRides = _t("多人骑乘坐骑\r")
ITEM_MORE_SEATER_RIDES_DESC.SingleSeaterRide = _t("坐骑\r")
ITEM_RIDES_ATTACK_DESC = {}
ITEM_RIDES_ATTACK_DESC.rides_attack = _t("可进行攻击\r")
ITEM_EQUIP_REQ_TEXT_DESC = {}
ITEM_EQUIP_REQ_TEXT_DESC.ProfessionReq1 = "%s  "
ITEM_EQUIP_REQ_TEXT_DESC.ProfessionReq2 = "%s  "
ITEM_EQUIP_REQ_TEXT_DESC.ProfessionReq3 = "%s  "
ITEM_EQUIP_REQ_TEXT_DESC.ProfessionReq4 = "%s  "
ITEM_EQUIP_REQ_TEXT_DESC.ProfessionReq5 = "%s  "
ITEM_EQUIP_REQ_TEXT_DESC.ProfessionReq6 = "%s  "
ITEM_EQUIP_REQ_TEXT_DESC.ProfessionReq7 = "%s  "
ITEM_EQUIP_REQ_TEXT_DESC.ProfessionReq8 = "%s  "
ITEM_EQUIP_REQ_TEXT_DESC.RaceReq1 = "%s "
ITEM_EQUIP_REQ_TEXT_DESC.RaceReq2 = "%s "
ITEM_EQUIP_REQ_TEXT_DESC.RaceReq3 = "%s "
ITEM_EQUIP_REQ_TEXT_DESC.RaceReq4 = "%s "
ITEM_EQUIP_REQ_TEXT_DESC.RaceReq5 = "%s "
ITEM_EQUIP_REQ_TEXT_DESC.RaceReqMask1 = _t("人类专用\r")
ITEM_EQUIP_ENERGY_CORE_DESC = {}
ITEM_EQUIP_ENERGY_CORE_DESC.Addon = _t("神炼增加属性\r")
ITEM_EQUIP_ENERGY_CORE_DESC.ActiveAddon = _t("核心等级%d属性加成\r")
ITEM_REFINE_LEVEL_DESC = {}
ITEM_REFINE_LEVEL_DESC.RefineLevel = _t("■ 基础聚能完美度%d（最高%d）\r   战力+%d\r")
ITEM_REFINE_LEVEL_DESC.RefineLevel_S = _t("■ 聚能完美度 %d/%d\r")
ITEM_REFINE_LEVEL_DESC.RefineLevel_A = _t("■ 基础聚能完美度%d（最高%d）\r   进阶聚能完美度%d（最高%d）\r   战力+%d\r")
EMPTY_E_ENHANCE_LEVEL = _t("■ 可聚能\r")
EMPTY_J_ENHANCE_LEVEL = _t("■ 可聚能\r")
ITEM_EMPLOYERS_NAME_DESC = {}
ITEM_EMPLOYERS_NAME_DESC.EmployersName = _t("主人 %s\r")
ITEM_REQ_GENDER_DESC = {}
ITEM_REQ_GENDER_DESC.ReqGender = _t("性别限制 %s\r")
ITEM_BOUNTY_SKILL_DESC = {}
ITEM_BOUNTY_SKILL_DESC.BountySkill = _t("%s技能 %s %d级%s\r")
ITEM_VALID_AREA_DESC = {}
ITEM_VALID_AREA_DESC.ValidArea = _t("应用区域 %s\r")
ITEM_BOUNTY_DESC = {}
ITEM_BOUNTY_DESC.BountyMaxhp = _t("生命值 %d/%d\r")
ITEM_BOUNTY_DESC.BountyMaxmp = _t("魔法值 %d/%d\r")
ITEM_BOUNTY_DESC.BountyHPGrow = _t("生命值成长率 %.2f\r")
ITEM_BOUNTY_DESC.BountyMPGrow = _t("魔法值成长率 %.2f\r")
ITEM_BOUNTY_DESC.BountyAttackGrow = _t("攻击成长率 %.2f\r")
ITEM_BOUNTY_DESC.BountyDefense = _t("防御力 %d\r")
ITEM_BOUNTY_DESC.BountyDefenseGrow = _t("防御成长率 %.2f\r")
ITEM_PET_APTT_STONE_DESC = {}
ITEM_PET_APTT_STONE_DESC.SuccessProb = _t("提升成功率 %.1f%%\r")
ITEM_PET_APTT_STONE_DESC.ApttAdd = _t("使资质提升 %.1f%%\r")
ITEM_PET_SKILL_UP_DESC = {}
ITEM_PET_SKILL_UP_DESC.PetSkillName = _t("将%d级的%s%s%s升至%d级\r")
ITEM_PET_SKILL_UP_DESC.SuccessProb = _t("提升成功率 %d%%\r")
ITEM_MEDICINE_TYPE_DESC = {}
ITEM_MEDICINE_TYPE_DESC.MedicineType0 = _t("使用效果 共可恢复%d点生命\r每次最多恢复%d点生命\r还可恢复%d点生命\r")
ITEM_MEDICINE_TYPE_DESC.MedicineType1 = _t("使用效果 共可恢复%d点能量\r每次最多恢复%d点能量\r还可恢复%d点能量\r")
ITEM_MEDICINE_TYPE_DESC.MedicineType2 = _t("使用效果 共可恢复%d点生命和%d点能量\r每次最多恢复%d点生命和%d点能量\r还可恢复%d点生命及%d点能量\r")
ITEM_MEDICINE_TYPE_DESC.MedicineType3 = _t("使用效果 恢复%d点生命\r之后的6秒内持续恢复%d点生命\r")
ITEM_MEDICINE_TYPE_DESC.MedicineType3A = _t("使用效果 恢复%d点生命\r")
ITEM_MEDICINE_TYPE_DESC.MedicineType4 = _t("使用效果 恢复%d点能量\r之后的6秒内持续恢复%d点能量\r")
ITEM_MEDICINE_TYPE_DESC.MedicineType4A = _t("使用效果 恢复%d点能量\r")
ITEM_MEDICINE_TYPE_DESC.MedicineType5 = _t("使用效果 恢复%d点生命及%d点能量\r之后的6秒内持续恢复%d点生命和%d点能量\r")
ITEM_MEDICINE_TYPE_DESC.MedicineType5A = _t("使用效果 恢复%d点生命及%d点能量\r")
ITEM_MEDICINE_TYPE_DESC.MedicineType6 = _t("共可恢复%d点生命\r每次最多恢复%d%%生命\r还可恢复%d点生命\r")
ITEM_MEDICINE_TYPE_DESC.MedicineType6A = _t("共可恢复%d点生命\r每次最多恢复%d%%生命\r")
ITEM_MEDICINE_TYPE_DESC.MedicineType7 = _t("持续恢复 %d元气\r")
ITEM_MOVE_SPEED_DESC = {}
ITEM_MOVE_SPEED_DESC.MoveSpeed = _t("^%06x移动速度 %.1f\r")
ITEM_MOVE_SPEED_DESC.FlyMoveSpeed = _t("^%06x飞行速度 %.1f\r")
ITEM_EQUIP_ATK_DISTANCE_DESC = {}
ITEM_EQUIP_ATK_DISTANCE_DESC.EquipAtkDistance = _t("攻击距离 %d\r")
ITEM_PREFIX_DESC = {}
ITEM_PREFIX_DESC.PrefixDes = _t("附加属性 %s\r")
ITEM_SUFFIX_DESC = {}
ITEM_SUFFIX_DESC.SuffixDes = _t("附加属性 %s\r")
ITEM_ENHANCE_ATTR_DESC = {[1] = _t("生命力+%d\r"), [13] = _t("地攻击+%d\r"), [14] = _t("水攻击+%d\r"), [15] = _t("火攻击+%d\r"), [16] = _t("风攻击+%d\r"), [113] = _t("雷攻击+%d\r"), [35] = _t("命中+%d\r"), [36] = _t("闪避+%d\r"), [39] = _t("防御力+%d\r"), [107] = _t("攻击力+%d\r"), [138] = _t("全属性攻+%d\r"), [43] = _t("暴击伤害+%d\r"), [45] = _t("暴伤减免+%d\r"), [147] = _t("光攻击+%d\r"), [152] = _t("主属性攻击+%d\r")}
ITEM_ENHANCE_ATTR_DESC_ADVANCE = {[1] = _t("生命力+%d[%d*%d%%]\r"), [13] = _t("地攻击+%d[%d*%d%%]\r"), [14] = _t("水攻击+%d[%d*%d%%]\r"), [15] = _t("火攻击+%d[%d*%d%%]\r"), [16] = _t("风攻击+%d[%d*%d%%]\r"), [113] = _t("雷攻击+%d[%d*%d%%]\r"), [35] = _t("命中+%d[%d*%d%%]\r"), [36] = _t("闪避+%d[%d*%d%%]\r"), [39] = _t("防御力+%d[%d*%d%%]\r"), [107] = _t("攻击力+%d[%d*%d%%]\r"), [138] = _t("全属性攻+%d[%d*%d%%]\r"), [43] = _t("暴击伤害+%d[%d*%d%%]\r"), [45] = _t("暴伤减免+%d[%d*%d%%]\r"), [147] = _t("光攻击+%d[%d*%d%%]\r"), [152] = _t("主属性攻击+%d[%d*%d%%]\r")}
ITEM_ENHANCE_EXTRA_DESC = {}
ITEM_ENHANCE_EXTRA_DESC.NOT_ACTIVATE = _t("未激活：%s (%d)\r")
ITEM_ENHANCE_EXTRA_DESC.ACTIVATE = _t("已激活：%s (%d)\r")
ITEM_ENHANCE_EXTRA_DESC.PERFECT = _t("★%d个完美激活\r   ")
ITEM_ENHANCE_DESC = {}
ITEM_ENHANCE_DESC.enhance_addon_group = "%s%s\r"
SUIT_TAG_LINE_DESC = _t("灵纹：%s\r")
SUIT_TAG_EXTRA_DESC = _t("灵纹可改造、转移\r")
ITEM_EQUIP_MAXATTACK_DESC = {}
ITEM_EQUIP_MAXATTACK_DESC.EquipMaxattack = _t("攻击力 %d～%d ")
ITEM_EQUIP_MAXATTACK_DESC.EquipMaxattack1 = _t("攻击力 %d ")
ITEM_EQUIP_MAXATTACK_DESC.EquipMaxattackAdd = _t("(+%d～%d)\r")
ITEM_EQUIP_MAXATTACK_DESC.EquipMaxattackAdd1 = "(+%d)\r"
ITEM_EQUIP_MAXATTACK_DESC.EquipMaxattackExtra = _t("(攻击力:%d～%d)")
ITEM_BOUNTY_ATTACK_MAX_DESC = {}
ITEM_BOUNTY_ATTACK_MAX_DESC.BountyAttackMax = _t("攻击 %d～%d\r")
ITEM_BOUNTY_ATTACK_MAX_DESC.BountyAttackMax1 = _t("攻击 %d\r")
ITEM_EQUIP_MAX_HP_DESC = {}
ITEM_EQUIP_MAX_HP_DESC.EquipMaxhp = _t("生命力 %d ")
ITEM_EQUIP_MAX_HP_DESC.EquipMaxhpAdd = "(+%d)\r"
ITEM_EQUIP_MAX_HP_DESC.EquipMaxhpExtra = _t("(生命力:%d)")
ITEM_EQUIP_MAX_MP_DESC = {}
ITEM_EQUIP_MAX_MP_DESC.EquipMaxmp = _t("魔力 %d ")
ITEM_EQUIP_MAX_MP_DESC.EquipMaxmpAdd = "(+%d)\r"
ITEM_EQUIP_MAX_MP_DESC.EquipMaxmpExtra = _t("(魔力:%d)")
ITEM_EQUIP_DEFENCE_DESC = {}
ITEM_EQUIP_DEFENCE_DESC.EquipDefence = _t("防御力 %d ")
ITEM_EQUIP_DEFENCE_DESC.EquipDefenceAdd = "(+%d)\r"
ITEM_EQUIP_DEFENCE_DESC.EquipDefenceExtra = _t("(防御力:%d)")
ITEM_PET_FOOD_USE_DESC = {}
ITEM_PET_FOOD_USE_DESC.PetFoodUse = _t("%s增加宠物体力 %d\r")
ITEM_EQUIP_POS_DESC = {}
ITEM_EQUIP_POS_DESC.EquipPos1 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos2 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos3 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos4 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos5 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos6 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos7 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos8 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos9 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos10 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos11 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos12 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos13 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos14 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos15 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos16 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos17 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos18 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos19 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos20 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos21 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos22 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos23 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos24 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos25 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos26 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos27 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos28 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos29 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos30 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos31 = "%s "
ITEM_EQUIP_POS_DESC.EquipPos32 = "%s "
ITEM_BOUNTY_LEVEL_DESC = {}
ITEM_BOUNTY_LEVEL_DESC.BountyLevel = _t("宠物等级 %d\r")
ITEM_EQUIP_APPRAISE_TEXT_DESC = {}
ITEM_EQUIP_APPRAISE_TEXT_DESC.AppraiseDesc = "%s\r"
ITEM_EQUIP_APPRAISE_TEXT_DESC.NotAppraise = _t("随机属性")
ITEM_EQUIP_APPRAISE_TEXT_DESC.FixedAppraise = _t("固定属性")
ITEM_EQUIP_MERGE_TEXT_DESC = ""
ITEM_EQUIP_MERGE_TEXT_DESC_TAG = _t("■ 增强融合\r")
STRING_EQUIP_ENHANCE_SUIT_DESC = _t("^ffff00★ 9件聚能激活(聚能1-12级）\r   单件大于%d完美度\r")
STRING_EQUIP_ENHANCE_SUIT_ADDON_DESC = _t("%s\r")
STRING_EQUIP_ENHANCE_SUIT_DESC_ADVANCE = _t("^ffff00★ 9件聚能激活（高于聚能12级）\r   单件大于%d完美度\r")
STRING_EQUIP_ENHANCE_SUIT_ADDON_DESC_ADVANCE = _t("%s\r")
ITEM_EQUIP_EXTRA_TEXT_DESC = ""
ITEM_EQUIP_EXTRA_TEXT_DESC_TAG = "%s\r"
ITEM_EQUIP_PROCESS_TEXT_DESC = _t("■ 符文（战力+%d)\r")
ITEM_EQUIP_PROCESS_TEXT_DESC1 = _t("■ 符文\r")
ITEM_EQUIP_PROCESS_TIMELEFT_DESC1 = _t("    剩余时间:%d秒")
ITEM_EQUIP_PROCESS_TIMELEFT_DESC2 = _t("    剩余时间:%d分")
ITEM_EQUIP_PROCESS_TIMELEFT_DESC3 = _t("    剩余时间:%d时%d分")
ITEM_EQUIP_PROCESS_TIMELEFT_DESC4 = _t("    剩余时间:%d天%d时")
ITEM_EQUIP_PROCESS_TIMELEFT_DESC5 = _t("    ★永久")
ITEM_EQUIP_PROCESS_TIMELEFT_DESC6 = _t("    已过期")
ITEM_EQUIP_PROCESS_EMPTY_TEXT_DESC = ""
ITEM_EQUIP_LEV_TEXT = _t("%s%d阶")
ITEM_EQUIP_WILLLEV_TEXT = _t("要求小宇宙等级 %d\r")
ITEM_PET_NAME = _t("%s宠物名: %s%s%s\r")
ITEM_PET = {}
ITEM_PET.AttackGrowth = _t("攻击成长率：%s%d%s\r")
ITEM_PET.DefenseGrowth = _t("防御成长率：%s%d%s\r")
ITEM_PET.HpGrowth = _t("生命成长率：%s%d%s\r")
ITEM_PET.Category = _t("%s宠物\r")
ITEM_PET.Attack = _t("攻击：%d - %d\r")
ITEM_PET.Defense = _t("防御：%d\r")
ITEM_PET.HpMax = _t("生命：%d\r")
ITEM_PET.AttackApt = _t("攻击资质：%.1f%%\r")
ITEM_PET.DefenseApt = _t("防御资质：%.1f%%\r")
ITEM_PET.HpApt = _t("生命资质：%.1f%%\r")
ITEM_BOUNTY_ATTACK_TALENT_DESC = {}
ITEM_BOUNTY_ATTACK_TALENT_DESC.BountyAttackTalent = _t("攻击天赋 %d级\r")
ITEM_BOUNTY_DEFENSE_TALENT_DESC = {}
ITEM_BOUNTY_DEFENSE_TALENT_DESC.BountyDefenseTalent = _t("防御天赋 %d级\r")
ITEM_BOUNTY_HP_TALENT_DESC = {}
ITEM_BOUNTY_HP_TALENT_DESC.BountyHPTalent = _t("生命天赋 %d级\r")
ITEM_BOUNTY_TRAIT_DESC = {}
ITEM_BOUNTY_TRAIT_DESC.BountyTraitMax = "%s "
ITEM_BOUNTY_TRAIT_DESC.BountyTraitMin = "%s "
ITEM_PET_CATCHER = {}
ITEM_PET_CATCHER.PlayerLevelReq = _t("使用需要人物达到%s\r")
ITEM_PET_CATCHER.LevelLimit = _t("只能对等级不超过%d的目标使用\r")
ITEM_PET_CATCHER.UseLimit = _t("对血量低于%d%%的宠物怪使用可以\r捕捉到一只^%06x%s的宠物%s\r")
ITEM_PET_CATCHER.Quality_0 = _t("一般的")
ITEM_PET_CATCHER.Quality_1 = _t("普通的")
ITEM_PET_CATCHER.Quality_2 = _t("良好的")
ITEM_PET_CATCHER.Quality_3 = _t("卓越的")
SAINT_CLOTH_OBTAIN = {}
SAINT_CLOTH_OBTAIN.not_obtained = _t("^ff0000未获得圣衣^f2f3f2")
SAINT_CLOTH_CLASS = {[0] = _t("^f2f3f2【青铜圣衣】^f2f3f2\r"), [1] = _t("^0184ff【白银圣衣】^f2f3f2\r"), [2] = _t("^ffff00【黄金圣衣】^f2f3f2\r"), [3] = _t("^ff0000【神圣衣】^f2f3f2\r")}
SAINT_CLOTH_FIGHT_POWER_DESC = {}
SAINT_CLOTH_FIGHT_POWER_DESC.fight_power = "\r          ^45d8ff%d^f2f3f2"
SAINT_CLOTH_FIGHT_POWER_DESC.fight_power_when_equipped = _t("★战力 ^ffc000%d^f2f3f2")
SAINT_CLOTH_ADDON = {}
SAINT_CLOTH_ADDON.addon_pack = _t("^O013^ff0000拥有者属性提升^O001 \r^ffc000★战力 %d^00ff00\r%s")
SAINT_CLOTH_ADDON.addon_pack_when_equipped = _t("\r^O013^f2f3f2装备后属性提升^O001 \r^ffc000★战力 %d^00ff00\r%s")
SAINT_CLOTH_ADDON.enhance_lev = _t("星铸等级 %d")
SAINT_CLOTH_REQ_DESC = {}
SAINT_CLOTH_REQ_DESC.req_level = _t("要求级别 %s")
SAINT_CLOTH_REQ_DESC.req_gender = _t("要求性别 %d\r")
SAINT_CLOTH_REQ_DESC.req_cosmos_level = _t("要求小宇宙等级 %d\r")
COSMOS_STAR_ADDON = "%s\r"
COSMOS_STAR_FIGHT_POWER = _t("^ffff00★战力 %d^f2f3f2\r")
COSMOS_STAR_NEED_PLAY_LEVEL = _t("激活等级 %s\r")
COSMOS_STAR_NEED_REALIZE_POINT = _t("需要小宇宙感悟 %d\r")
COSMOS_STAR_UNACTIVED = _t("^ff0000未激活^f2f3f2\r")
COSMOS_STAR_ACTIVED = ""
COSMOS_STAR_NO_STONE = _t("^ff0000左键点击可镶嵌星魂^f2f3f2\r")
COSMOS_STAR_HAVE_STONE = _t("^f2f3f2左键点击可替换星魂\r右键点击可升级星魂^f2f3f2\r")
COSMOS_STAR_ACCEPT_COLOR = {[0] = _t("·^ff0000【日相】^f2f3f2\r"), [1] = _t("·^0184ff【月相】^f2f3f2\r"), [2] = _t("·^ffff00【主序】^f2f3f2\r"), [3] = _t("^f2f3f2\r"), [4] = _t("^f2f3f2\r"), [5] = _t("^f2f3f2\r"), [6] = _t("^f2f3f2\r")}
COSMOS_STAGE_FIGHT_POWER = _t("^ffff00★战力 %d^f2f3f2")
COSMOS_STAGE_ADDON = "%s"
COSMOS_RANK_STAR_NEED_RANK_LEVEL = _t("激活小宇宙等级 %d\r")
COSMOS_RANK_STAR_NEED_SKILL_POINT = _t("需要技能感悟 %d\r")
ITEM_ENDURE_DESC = {}
ITEM_ENDURE_DESC.Endure = _t("%s耐久度 %d/%d")
ITEM_ENDURE_DESC.Zero = _t("，修理后才能装备")
ITEM_TESSERA_ADD_DESC = {}
ITEM_TESSERA_ADD_DESC.TesseraAdd = _t("镶嵌效果 %s\r")
ITEM_MASTER_REQ_LEVEL_DESC = {}
ITEM_MASTER_REQ_LEVEL_DESC.MasterReqLevel = _t("炼化等级要求 %d级\r")
ITEM_PET_REQ_LEVEL_DESC = {}
ITEM_PET_REQ_LEVEL_DESC.PetReqLevel = _t("宠物等级要求 %d\r")
ITEM_PET_REQ_LEVEL_DESC.PetReqLevel1 = _t("当前没有出战的宠物\r")
ITEM_PET_REQ_LEVEL_DESC.PetSummonLevel = _t("宠物携带等级要求 %d\r")
ITEM_BOUNTY_REQ_LEVEL_DESC = {}
ITEM_BOUNTY_REQ_LEVEL_DESC.BountyReqLevel = _t("等级要求 %d\r")
ITEM_BOUNTY_REQ_LEVEL_DESC.BountyReqLevel1 = _t("当前没有选中的宠物\r")
ITEM_EQUIP_SOUL_1_DESC = {}
ITEM_EQUIP_SOUL_1_DESC.EquipSoul1 = _t("装备强化到%d级将触发初级灵魂形态\r")
ITEM_EQUIP_SOUL_1_DESC.EquipSoul2 = _t("装备强化到%d级将触发中级灵魂形态\r")
ITEM_EQUIP_SOUL_1_DESC.strEquipSoul3 = _t("装备强化到%d级将触发高级灵魂形态\r")
ITEM_BE_COLLECTED_DESC = {}
ITEM_BE_COLLECTED_DESC.BeCollected = _t("已收藏\r")
ITEM_BE_COLLECTED_DESC.NotBeCollected = _t("未收藏\r")
ITEM_PET_GROWTH_STONE_DESC = {}
ITEM_PET_GROWTH_STONE_DESC.type0 = _t("增加宠物攻击成长率%d点成长度\r")
ITEM_PET_GROWTH_STONE_DESC.type1 = _t("增加宠物防御成长率%d点成长度\r")
ITEM_PET_GROWTH_STONE_DESC.type2 = _t("增加宠物生命成长率%d点成长度\r")
ITEM_SOUL_STONE = {}
ITEM_SOUL_STONE.SoulStoneType1 = _t("力量\r")
ITEM_SOUL_STONE.SoulStoneType2 = _t("灵力\r")
ITEM_SOUL_STONE.SoulStoneType3 = _t("暴伤\r")
ITEM_SOUL_STONE.SoulStoneType4 = _t("大攻击\r")
ITEM_SOUL_STONE.SoulStoneType5 = _t("攻击\r")
ITEM_SOUL_STONE.SoulStoneType6 = _t("附加伤害\r")
ITEM_SOUL_STONE.SoulStoneType7 = _t("防御\r")
ITEM_SOUL_STONE.SoulStoneType8 = _t("耐力\r")
ITEM_SOUL_STONE.SoulStoneType9 = _t("体力\r")
ITEM_SOUL_STONE.SoulStoneType10 = _t("生命\r")
ITEM_SOUL_STONE.Level1 = _t("初级")
ITEM_SOUL_STONE.Level2 = _t("中级")
ITEM_SOUL_STONE.Level3 = _t("高级")
ITEM_SOUL_STONE.StrAddon = _t("基础属性: %s\r")
ITEM_SOUL_STONE.Quality = _t("品质:%d品\r")
ITEM_SOUL_STONE.CurBright = _t("魂力当前值:%d\r")
ITEM_SOUL_STONE.InitBright = _t("魂力初始值:%d\r")
ITEM_SOUL_STAR_STONE_LEVEL_UP = {}
ITEM_SOUL_STAR_STONE_LEVEL_UP.Desc = _t("%s可以提升星魂的魂力%d点\r有小概率使魂力提升%d点\r星魂的最大魂力不能超过%d\r")
ITEM_EQUIP_BASEPROP_DESC = {}
ITEM_EQUIP_BASEPROP_DESC.Strength = _t("%s力量 %d\r")
ITEM_EQUIP_BASEPROP_DESC.Stamina = _t("%s体力 %d\r")
ITEM_EQUIP_BASEPROP_DESC.Mana = _t("%s灵力 %d\r")
ITEM_EQUIP_BASEPROP_DESC.Durability = _t("%s耐力 %d\r")
ITEM_EQUIP_BASEPROP_EXTRA_DESC = {}
ITEM_EQUIP_BASEPROP_EXTRA_DESC.Strength = _t("力量")
ITEM_EQUIP_BASEPROP_EXTRA_DESC.Stamina = _t("体力")
ITEM_EQUIP_BASEPROP_EXTRA_DESC.Mana = _t("灵力")
ITEM_EQUIP_BASEPROP_EXTRA_DESC.Durability = _t("耐力")
ITEM_EQUIP_ELEMENTDMG_DESC = {}
ITEM_EQUIP_ELEMENTDMG_DESC.Earth = _t("%s地攻击 %d\r")
ITEM_EQUIP_ELEMENTDMG_DESC.Water = _t("%s水攻击 %d\r")
ITEM_EQUIP_ELEMENTDMG_DESC.Fire = _t("%s火攻击 %d\r")
ITEM_EQUIP_ELEMENTDMG_DESC.Wind = _t("%s风攻击 %d\r")
ITEM_EQUIP_ELEMENTDMG_DESC.Thunder = _t("%s雷攻击 %d\r")
ITEM_EQUIP_ELEMENTDMG_DESC.Light = _t("%s光攻击 %d\r")
ITEM_EQUIP_ELEMENTDMG_EXTRA_DESC = {}
ITEM_EQUIP_ELEMENTDMG_EXTRA_DESC.Earth = _t("(地攻击:%d)")
ITEM_EQUIP_ELEMENTDMG_EXTRA_DESC.Water = _t("(水攻击:%d)")
ITEM_EQUIP_ELEMENTDMG_EXTRA_DESC.Fire = _t("(火攻击:%d)")
ITEM_EQUIP_ELEMENTDMG_EXTRA_DESC.Wind = _t("(风攻击:%d)")
ITEM_EQUIP_ELEMENTDMG_EXTRA_DESC.Thunder = _t("(雷攻击:%d)")
ITEM_EQUIP_FIGHT_POWER_BASE = _t("★战力 %-5d\r")
ITEM_EQUIP_FIGHT_POWER_DESC = _t("★战力 %-24d \r")
ITEM_EQUIP_FIGHT_POWER_ENHANCE = _t("★战力 %d")
ITEM_EQUIP_FIGHT_POWER = " + %d\r"
ITEM_GUARD_STAR = {}
ITEM_GUARD_STAR.GuardPoint = _t("守护值 %d\r")
ITEM_GUARD_STAR.GuardLevel1 = _t("可吸收的守护星等级下限： %d\r")
ITEM_GUARD_STAR.GuardLevel2 = _t("可吸收的守护星等级上限： %d\r")
ITEM_DECOMPSE = {}
ITEM_DECOMPSE.Item = _t("%s分解: %s%s")
STAR_SOUL = {}
STAR_SOUL_ADDON_PACK = "%s\r"
STAR_SOUL_ADDON_PACK_COMPARE = "%s\t%s"
STAR_SOUL_NEXT_LEVEL = _t("^ffff00下一等级:                     ^00ff00%d级")
STAR_SOUL_BURST_DESC = _t("^ff0000^O013爆发属性")
STAR_SOUL_BURST_ADDON_PACK = "%s\r"
STAR_SOUL_BURST_ADDON_PACK_COMPARE = "%s\t%s"
STAR_SOUL_BURST_BUFF_PACK = _t("%s\r★第%d阶段爆发\r")
STAR_SOUL_FIGHT_POWER_NULL = _t("\r")
STAR_SOUL_FIGHT_POWER_COMPARE = _t("★战力 %d\t%s")
STAR_SOUL_VALUE_UP = _t("↑ ")
STAR_SOUL_VALUE_DOWN = _t("↓ ")
STAR_SOUL_EXP = _t("\r^ffff00经验 ^00ff00%d^f2f3f2/%d\r")
STAR_SOUL_LEV = _t("^ffff00等级 ^00ff00%d^f2f3f2         ")
STAR_SOUL_LEV_EXP1 = _t("等级 %s%d")
STAR_SOUL_LEV_EXP2 = _t("                     经验 %s%d%s/%d\r")
STAR_SOUL_SKILL_UP = _t("↑ 技能提升")
STAR_SOUL_CLASS = {[0] = "", [1] = _t("护盾"), [2] = _t("神速"), [3] = _t("蛮力"), [4] = _t("韧性"), [5] = _t("穿透"), [6] = _t("生命"), [7] = "", [8] = "", [9] = "", [10] = ""}
STAR_SOUL_CLASS_HINT = _t("带有<%s>爆发属性的小宇宙中\r只能同时注入一个")
STAR_SOUL_COLOR = {[1] = _t("^ff0000【日相】^f2f3f2^O001"), [2] = _t("^0184ff【月相】^f2f3f2^O001"), [3] = _t("^ffff00【主序】^f2f3f2^O001")}
STAR_SOUL_BOX_DESC = _t("使用后获得%d级星魂:%s")
EQUIP_SUIT_TAG_DESC = {[1] = _t("I·格里芬之爪"), [2] = _t("II·金苹果"), [3] = _t("III·丰饶之角"), [4] = _t("IV·弥诺陶斯"), [5] = _t("V·塞壬之羽"), [6] = _t("VI·地狱之石"), [7] = _t("VII·梅杜莎"), [8] = _t("VIII·许德拉"), [9] = _t("IX·力量之杯"), [10] = _t("X·涅柔斯之环"), [11] = _t("XI·桂冠"), [12] = _t("XII·胜利之矛"), [13] = _t("XIII·英雄"), [14] = _t("XIV·复仇"), [15] = _t("XV·泰坦之力"), [16] = _t("XVIII·命运")}
EQUIP_SUIT_TAG_DESC_TITLE = _t("灵纹：%s\r")
EQUIP_SUIT_TAG_DESC_TITLE1 = _t("灵纹：%s\r")
EQUIP_SUIT_TAG_DESC_STR1 = "[4]%s\r"
EQUIP_SUIT_TAG_DESC_STR2 = "[5]%s\r"
EQUIP_SUIT_TAG_DESC_STR3 = "[6]%s\r"
ITEM_COMBATPET_EQUIP_DESC = {}
ITEM_COMBATPET_EQUIP_DESC.DESC = _t("守护星专用装备\r")
ITEM_COMBATPET_EQUIP_DESC.Part_Type_Head = _t("装备部位 战盔\r")
ITEM_COMBATPET_EQUIP_DESC.Part_Type_Hair = _t("装备部位 战靴\r")
ITEM_COMBATPET_EQUIP_DESC.Part_Type_Body = _t("装备部位 战甲\r")
ITEM_COMBATPET_EQUIP_DESC.Gender_Male = _t("性别限制 男\r")
ITEM_COMBATPET_EQUIP_DESC.Gender_Female = _t("性别限制 女\r")
ITEM_COMBATPET_EQUIP_DESC.Gender_None = _t("性别限制 无\r")
ITEM_COMBATPET_EQUIP_DESC.LevelReq = _t("要求等级:%d\r")
ITEM_COMBATPET_EQUIP_DESC.Attack = _t("攻击力 %d\r")
ITEM_COMBATPET_EQUIP_DESC.ElementAttack = _t("属性攻击力 %d\r")
ITEM_COMBATPET_EQUIP_DESC.Hit = _t("命中 %d\r")
ITEM_COMBATPET_EQUIP_DESC.Critical = _t("暴击率 %d%%\r")
ITEM_COMBATPET_EQUIP_DESC.Power = _t("★战力 %-5d\r")
ITEM_COMBATPET_EQUIP_DESC.Aptitude = _t("资质 %d\r")
ITEM_COMBATPET_EQUIP_DESC.AddonDesc = _t("增加人物属性\r")
ITEM_COMBATPET_EQUIP_DESC.AddonDescCompare = _t("增加人物属性               \v下一级\r")
ITEM_COMBATPET_EQUIP_DESC.Addon1 = _t("  %s\r")
ITEM_COMBATPET_EQUIP_DESC.Addon2 = _t("  %s\r")
ITEM_COMBATPET_EQUIP_DESC.Addon3 = _t("  %s\r")
ITEM_COMBATPET_EQUIP_DESC.Addon4 = _t("  %s\r")
ITEM_COMBATPET_EQUIP_DESC.AddonCompare = _t("%s            \v%s\r")
ITEM_PET_SKILL_BOOK_DESC = {}
ITEM_PET_SKILL_BOOK_DESC.Slot = _t("放入技能格\r%s\r")
ITEM_PET_SKILL_BOOK_DESC.Skill_Name = _t("附带技能:%s")
ITEM_PET_SKILL_BOOK_DESC.Skill_Level = _t("%d级\r")
ITEM_COMBATPET_DESC = {}
ITEM_COMBATPET_DESC.StarLevel = _t("星级:%s\r")
ITEM_COMBATPET_DESC.Max_Level = _t("等级上限:%s\r")
ITEM_COMBATPET_DESC.Aptitude = _t("资质:%d/%d\r")
ITEM_COMBATPET_DESC.Max_Aptitude = _t("最大资质:%d\r")
ITEM_COMBATPET_DESC.Gender_Male = _t("性别:男\r")
ITEM_COMBATPET_DESC.Gender_Female = _t("性别:女\r")
ITEM_COMBATPET_DESC.Max_Skill_Slots = _t("技能格数:%d\r")
ITEM_COMBATPET_DESC.Damage = _t("攻击力:%d\r")
ITEM_COMBATPET_DESC.ElementDamage = _t("全属性攻击力:%d\r")
ITEM_COMBATPET_DESC.Hit = _t("命中:%d\r")
ITEM_COMBATPET_DESC.Critical = _t("暴击率:%d%%\r")
ITEM_COMBATPET_DESC.Equip1 = _t("战盔:%s\r")
ITEM_COMBATPET_DESC.Equip2 = _t("战靴:%s\r")
ITEM_COMBATPET_DESC.Equip3 = _t("战甲:%s\r")
ITEM_COMBATPET_DESC.Skill_Name = _t("技能:%s")
ITEM_COMBATPET_DESC.Skill_Level = _t("%d级\r")
ITEM_COMBATPET_DESC.Player_Level_Req = _t("人物等级要求:%s\r")
ITEM_COMBATPET_DESC.Fight_Power = _t("★战力 %-5d\r")
ITEM_COMBATPET_DESC.Level = _t("Lv %d")
ITEM_COMBATPET_DESC.Valid_Level = _t("Lv %d^ff0000(有效Lv %d)\r")
ITEM_COMBATPET_DESC.Addon_Prop = _t("附加人物属性:\r")
ITEM_TASK_TRIG_DESC = {}
ITEM_TASK_TRIG_DESC.TITLE = _t("%s打开后获得：\r%s银河狂欢币*5\r")
ITEM_TASK_TRIG_DESC.EXP = _t("经验：%.0f\r")
ITEM_TASK_TRIG_DESC.STORE_EXP = _t("储存经验：%.0f\r")
ITEM_TASK_TRIG_DESC.EXP2 = _t("历练：%.0f\r")
ITEM_TASK_TRIG_DESC.STORE_EXP2 = _t("储存历练：%.0f\r")
ITEM_TASK_TRIG_DESC.BIND_MONEY = _t("金券：%d\r")
ITEM_TASK_TRIG_DESC.TASK_FINISH_COUNT = _t("还可以使用%d次\r")
ITEM_TASK_TRIG_DESC.TASK_TIME_LIMIT = _t("^FF0000一天后可继续使用^F2F3F2\r")
ITEM_ARTIFACT_DESC = {}
ITEM_ARTIFACT_DESC.SECTION = _t("神铸： %d/%d")
ITEM_ARTIFACT_DESC.POWER = _t("神力值: %d")
ITEM_ARTIFACT_DESC.UNIQUE = _t("唯一属性")
ITEM_ARTIFACT_DESC.STATE = _t("境界属性")
ITEM_ARTIFACT_DESC.STATE_1 = _t("青铜之境: %d/%d级")
ITEM_ARTIFACT_DESC.STATE_2 = _t("白银之境: %d/%d级")
ITEM_ARTIFACT_DESC.STATE_3 = _t("黄金之境: %d/%d级")
ITEM_ARTIFACT_DESC.STATE_4 = _t("神圣之境: %d/%d级")
ITEM_ARTIFACT_DESC.STATE_5 = _t("完美之境: %d/%d级")
ITEM_ARTIFACT_DESC.UNACTIVE = _t("(神力值达到%d后激活)")
ITEM_ARTIFACT_DESC.SKILL = _t("神器技能")
ITEM_SOULARMOR_GEM = {}
ITEM_SOULARMOR_GEM.StrAddon = _t("宝石属性\r%s\r")
ITEM_SOULARMOR_GEM.StrNextAddon = _t("下一级:%s%s\r")
ITEM_SOULARMOR_GEM.StrExp = _t("附带经验：%d/%d\r")
ITEM_SOULARMOR_GEM.FullLev = _t("已满级\r")
SOULARMOR_DESC = {}
SOULARMOR_DESC.NAME_LEV_ACTIVE = _t("%s\r铠甲等级%d级")
SOULARMOR_DESC.NAME_LEV = _t("%s\r^FF0000未激活")
SOULARMOR_DESC.ADDON_PACK = _t("附带属性\r%s")
SOULARMOR_DESC.GEM_EMBED = _t("宝石镶嵌（最高等级%d级）")
SOULARMOR_DESC.GEM_INFO = _t("%s%s+%d")
SOULARMOR_DESC.GEM_EMPTY = _t("^FFFFFF空")
SOULARMOR_DESC.NEXT_PLAYER_LEV = _t("下一级\r等级%d需要等级：%s")
SOULARMOR_DESC.NEXT_ADDON_PACK = _t("等级%d附带:\r%s")
SOULARMOR_DESC.NEXT_GEM_NUM = _t("下级最多镶嵌灵魂宝石%d颗，最高等级%d级")
SOULARMOR_GEM_DESC_EXTRA_OTHER = _t("可以镶嵌除冥王星外的所有宝石,同种宝石只能镶嵌一颗")
SOULARMOR_GEM_DESC_EXTRA_ALL = _t("可以镶嵌所有宝石,同种宝石只能镶嵌一颗")
ASSISTSTAR_DESC = {}
ASSISTSTAR_DESC.LEV = _t("强化等级 %d/%d")
ASSISTSTAR_DESC.REQ_LEV = _t("装备需求强化等级:%d")
ASSISTSTAR_DESC.SAINT_CLOTH = _t("[%s]星铸到%d级后激活")
ASSISTSTAR_DESC.SKILL_POINT1 = _t("觉醒值%d (达到%d级增加%d点)")
ASSISTSTAR_DESC.SKILL_POINT2 = _t("觉醒值%d")
ASSISTSTAR_DESC.OWN_ADDON_HEAD1 = _t("^00FF00拥有者属性\v\v下一级")
ASSISTSTAR_DESC.OWN_ADDON_HEAD2 = _t("^00FF00拥有者属性^N")
ASSISTSTAR_DESC.EQUIP_ADDON_HEAD1 = _t("^00FF00装备者属性\v\v下一级")
ASSISTSTAR_DESC.EQUIP_ADDON_HEAD2 = _t("^00FF00装备者属性^N")
ASSISTSTAR_DESC.ADDON = _t("%s\v\v%s")
ASSISTSTAR_DESC.COMBO_HEAD = _t("^00FFFF星灵共鸣（满级共鸣属性）")
ASSISTSTAR_DESC.COMBO_NAME = _t("^FFFF00【%s】^FFFFFF %s")
ASSISTSTAR_DESC.COMBO_END = _t("^FF0000共鸣组合中的所有星灵均达到一定等级后将提升共鸣等级，最高为5级")
ASSISTSTAR_DESC.COMBO_DETAIL_NAME = _t("^%06x【%sLv%d】^N")
ASSISTSTAR_DESC.COMBO_DETAIL_ADDON1 = _t("^00FF00可获得属性\v\v下一级")
ASSISTSTAR_DESC.COMBO_DETAIL_ADDON2 = _t("^00FF00可获得属性")
ASSISTSTAR_DESC.COMBO_DETAIL_NEXT = _t("^00FF00下一级需要:^N")
ASSISTSTAR_DESC.COMBO_DETAIL_STAR = _t("%s%sLv%d^N")
GOLDENSOUL = {}
GOLDENSOUL.LEV1 = _t("等级%d\v\v下一级")
GOLDENSOUL.GOLDEN_VALUE1 = _t("黄金潜力+%d\v\v↑ %d")
GOLDENSOUL.HOLY_VALUE1 = _t("神圣潜力+%d\v\v↑ %d")
GOLDENSOUL.ADDON = _t("%s\v\v%s")
GOLDENSOUL.LEV2 = _t("等级%d")
GOLDENSOUL.GOLDEN_VALUE2 = _t("黄金潜力%d")
GOLDENSOUL.HOLY_VALUE2 = _t("神圣潜力%d")
GOLDENSOUL.SAINT_CLOTH_ENH = _t("圣衣装备属性提升%.1f%%")
ENERGY_CORE_DESC = {}
ENERGY_CORE_DESC.LEV = _t("等级: %d")
ENERGY_CORE_DESC.TYPE = _t("类型: %d")
ENERGY_CORE_DESC.INIT_EXP = _t("初始经验:%d")
ENERGY_CORE_DESC.CUR_EXP = _t("拥有经验:%d")
ENERGY_CORE_DESC.NEXT_LEV = _t("下一等级：")
ENERGY_CORE_DESC.FIGHT_POWER = _t("★战力 %d")
ENERGY_CORE_DESC_PACK = "%s\r"
ENERGY_CORE_DESC_PACK_COMPARE = "%s\t%s"

